# Generated by Django 4.2.3 on 2023-07-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructorName', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('courseUnit', models.CharField(max_length=100)),
                ('knowledge', models.IntegerField(choices=[(20, 'Poor'), (40, 'Fair'), (60, 'Good'), (80, 'Very Good'), (100, 'Excellent')])),
                ('communication', models.IntegerField(choices=[(20, 'Poor'), (40, 'Fair'), (60, 'Good'), (80, 'Very Good'), (100, 'Excellent')])),
                ('teachingStyle', models.IntegerField(choices=[(20, 'Poor'), (40, 'Fair'), (60, 'Good'), (80, 'Very Good'), (100, 'Excellent')])),
                ('responsiveness', models.IntegerField(choices=[(20, 'Poor'), (40, 'Fair'), (60, 'Good'), (80, 'Very Good'), (100, 'Excellent')])),
                ('additional_comments', models.TextField()),
            ],
        ),
    ]
