# Generated by Django 4.2.3 on 2023-08-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Facility name')),
                ('facility_college', models.CharField(max_length=100, verbose_name='College of facility')),
                ('facility_accessibility', models.CharField(choices=[('fully', 'Fully accessible'), ('partial', 'Partially accessible'), ('not', 'Not accessible')], max_length=20, verbose_name='Facility accessibility')),
                ('cleanliness', models.CharField(choices=[('very_good', 'Very Good'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('very_poor', 'Very Poor')], max_length=20, verbose_name='Cleanliness and Hygiene')),
                ('maintenance', models.CharField(choices=[('very_good', 'Very Good'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('very_poor', 'Very Poor')], max_length=20, verbose_name='Maintenance')),
                ('safety', models.CharField(choices=[('very_good', 'Very Good'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('very_poor', 'Very Poor')], max_length=20, verbose_name='Safety and Security')),
                ('resource_availability', models.CharField(choices=[('very_good', 'Very Good'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('very_poor', 'Very Poor')], max_length=20, verbose_name='Resource Availability')),
                ('facility_rating', models.CharField(choices=[('very_good', 'Very Good'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('very_poor', 'Very Poor')], max_length=20, verbose_name='Overall facility rating')),
                ('comment', models.TextField(blank=True, verbose_name='Additional Comments or Suggestions')),
            ],
        ),
    ]
