# Generated by Django 4.2.3 on 2023-08-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_facilityfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityfeedback',
            name='cleanliness',
            field=models.CharField(choices=[('very_good', 'Very Good'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('very_poor', 'Very Poor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='facilityfeedback',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='facilityfeedback',
            name='facility_accessibility',
            field=models.CharField(choices=[('fully', 'Fully accessible'), ('partial', 'Partially accessible'), ('not', 'Not accessible')], max_length=20),
        ),
        migrations.AlterField(
            model_name='facilityfeedback',
            name='facility_college',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='facilityfeedback',
            name='facility_rating',
            field=models.CharField(choices=[('very_good', 'Very Good'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('very_poor', 'Very Poor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='facilityfeedback',
            name='maintenance',
            field=models.CharField(choices=[('very_good', 'Very Good'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('very_poor', 'Very Poor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='facilityfeedback',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='facilityfeedback',
            name='resource_availability',
            field=models.CharField(choices=[('very_good', 'Very Good'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('very_poor', 'Very Poor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='facilityfeedback',
            name='safety',
            field=models.CharField(choices=[('very_good', 'Very Good'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('very_poor', 'Very Poor')], max_length=20),
        ),
    ]
