# Generated by Django 4.2.3 on 2023-08-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_facilityfeedback_cleanliness_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=100)),
                ('courseCode', models.CharField(max_length=100)),
                ('courseDescription', models.CharField(max_length=1000)),
                ('effectiveness', models.IntegerField(choices=[(20, 'Poor'), (40, 'Fair'), (60, 'Good'), (80, 'Very Good'), (100, 'Excellent')])),
                ('interest', models.IntegerField(choices=[(20, 'Poor'), (40, 'Fair'), (60, 'Good'), (80, 'Very Good'), (100, 'Excellent')])),
                ('improvement', models.TextField()),
            ],
        ),
    ]
