# Generated by Django 4.2.3 on 2023-08-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_studentdetails'),
        ('website', '0004_course'),
    ]

    operations = [
    ]
